openapi: 3.0.0
info:
  title: Netris API
  version: v2
security:
  - cookieAuth: []
paths:
  /api/v2/vnet:
    get:
      tags:
        - V-Net
      summary: Request for getting V-Net list.
      parameters:
        - name: filterBySites
          in: query
          description: 'Filter result by Site id.'
          schema:
            $ref: '#/components/schemas/filterBySites'
        - name: filterByVpc
          in: query
          description: |
            Filter result by VPC id. If no VPC ID is specified, the results will be filtered based on the default VPC.
          schema:
            $ref: '#/components/schemas/filterByVpc'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResListBody'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResErrorBody'
    post:
      tags:
        - V-Net
      summary: Request for adding V-Net.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vnetAddBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResAddBody'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResErrorBody'
  /api/v2/vnet/{id}:
    get:
      tags:
        - V-Net
      summary: Request for getting V-Net info.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific V-Net
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResListByIdBody'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResErrorBody'
    put:
      tags:
        - V-Net
      summary: Request for editting V-Net.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The id of a specific V-Net
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vnetEditBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResAddBody'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResErrorBody'
    delete:
      tags:
        - V-Net
      summary: Request for deleting V-Net.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the V-Net.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResDeleteBody'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vnetResErrorBody'
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Web Service Cookie
  schemas:
    filterByVpc:
      type: array
      items:
        type: integer
    filterBySites:
      type: array
      items:
        type: integer
    vnetAddBody:
      type: object
      required:
        - name
        - tenant
        - sites
      properties:
        name:
          type: string
          example: uniqueName
        tenant:
          type: object
          properties:
            id:
              type: number
              example: 23
            name:
              type: string
              example: Unix
          description: ""
        sites:
          type: array
          description: Ports from these sites will be allowed to participate to the V-Net. Multi-site circuits are possible for sites connected through a backbone port.
          items:
            type: object
            properties:
              id:
                type: number
                example: 1
              name:
                type: string
                example: Santa-Clara
            description: ""
        vlan:
          description: Required only when selected site is not Netris managed
          oneOf:
            - type: string
              enum:
                - auto
            - type: integer
        guestTenants:
          type: array
          description: List of tenants allowed to add/edit/remove ports to the V-Net but not allowed to manage other parameters of the circuit.
          items:
            type: object
            properties:
              id:
                type: number
                example: 34
              name:
                type: string
                example: Guest tenant
            description: ""
        state:
          type: string
          enum:
            - active
            - disabled
          example: active
        provisioning:
          type: boolean
          example: false
        vlanAware:
          type: boolean
          example: true
        l3vpn:
          type: boolean
          example: true
        nativeVlan:
          oneOf:
            - description: Native VLAN ID
              type: string
              nullable: true
            - description: Native VLAN ID.
              type: integer
              minimum: 1
              maximum: 4094
              example: 1
        vlans:
          type: string
          example: 1,3,4
          description: Required for only vlan-aware v-nets (vlanAware == true).
        gateways:
          type: array
          items:
            type: object
            properties:
              prefix:
                type: string
                example: 10.0.0.1/24
              vlan:
                type: number
                example: 1
                description: Required for only vlan-aware v-nets (vlanAware == true)
              dhcpEnabled:
                type: boolean
                description: Is the DHCP service enabled for the V-Net
                example: true
              dhcp:
                type: object
                description: It is optional to specify the object, as the backend will automatically fill it on behalf of you
                properties:
                  start:
                    type: string
                    example: 10.0.0.2
                  end:
                    type: string
                    example: 10.0.0.254
                  optionSet:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 21
                      name:
                        type: string
                        example: MyDefaultOptionSet
        ports:
          type: array
          items:
            $ref: '#/components/schemas/vnetPortEditBody'
        tags:
          type: array
          items:
            type: string
          example:
            - tag1
            - tag2
    vnetEditBody:
      type: object
      properties:
        name:
          type: string
          example: uniqueName
        sites:
          type: array
          description: Ports from these sites will be allowed to participate to the V-Net. Multi-site circuits are possible for sites connected through a backbone port.
          items:
            type: object
            properties:
              id:
                type: number
                example: 1
              name:
                type: string
                example: Santa-Clara
            description: ""
        vlan:
          description: Required only when selected site is not Netris managed
          oneOf:
            - type: string
              enum:
                - auto
            - type: integer
        guestTenants:
          type: array
          description: List of tenants allowed to add/edit/remove ports to the V-Net but not allowed to manage other parameters of the circuit.
          items:
            type: object
            properties:
              id:
                type: number
                example: 34
              name:
                type: string
                example: Guest tenant
            description: ""
        state:
          type: string
          enum:
            - active
            - disabled
          example: active
        provisioning:
          type: boolean
          example: false
        l3vpn:
          type: boolean
          example: true
        nativeVlan:
          oneOf:
            - description: Native VLAN ID
              type: string
              nullable: true
            - description: Native VLAN ID.
              type: integer
              minimum: 1
              maximum: 4094
              example: 1
        vlans:
          type: string
          example: 1,3,4
          description: Required for only vlan-aware v-nets (vlanAware == true).
        gateways:
          type: array
          items:
            type: object
            properties:
              prefix:
                type: string
                example: 10.0.0.1/24
              vlan:
                type: number
                example: 1
                description: Required for only vlan-aware v-nets (vlanAware == true)
              dhcpEnabled:
                type: boolean
                description: Is DHCP service enabled for the V-Net
                example: true
              dhcp:
                description: It's optional to specify the object, as the backend will automatically fill it on behalf of you
                type: object
                properties:
                  start:
                    type: string
                    example: 10.0.0.2
                  end:
                    type: string
                    example: 10.0.0.254
                  optionSet:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 21
                      name:
                        type: string
                        example: MyDefaultOptionSet
        ports:
          type: array
          items:
            $ref: '#/components/schemas/vnetPortEditBody'
        tags:
          type: array
          items:
            type: string
          example:
            - tag1
            - tag2
    vnetBody:
      allOf:
        - $ref: '#/components/schemas/vnetsBody'
        - $ref: '#/components/schemas/vnetPortBody'
    vnetsBody:
      type: object
      required:
        - name
        - tenant
        - sites
      properties:
        name:
          type: string
          example: uniqueName
        tenant:
          type: object
          properties:
            id:
              type: number
              example: 23
            name:
              type: string
              example: Unix
          description: ""
        sites:
          type: array
          description: Ports from these sites will be allowed to participate to the V-Net. Multi-site circuits are possible for sites connected through a backbone port.
          items:
            type: object
            properties:
              id:
                type: number
                example: 1
              name:
                type: string
                example: Santa-Clara
            description: ""
        vpc:
          type: object
          nullable: true
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: DefaultVpc
            isDefault:
              type: boolean
              example: true
            isSystem:
              type: boolean
              example: false
        vlan:
          description: Required only when selected site is not Netris managed
          type: integer
          example: 567
        guestTenants:
          type: array
          description: List of tenants allowed to add/edit/remove ports to the V-Net but not allowed to manage other parameters of the circuit.
          items:
            type: object
            properties:
              id:
                type: number
                example: 34
              name:
                type: string
                example: Guest tenant
            description: ""
        state:
          type: string
          enum:
            - active
            - disabled
            - unmanaged
          example: active
        provisioning:
          type: boolean
          example: false
        vlanAware:
          type: boolean
          example: true
        l3vpn:
          type: boolean
          example: false
        nativeVlan:
          oneOf:
            - description: Native VLAN ID
              type: string
              nullable: true
            - description: Native VLAN ID.
              type: integer
              minimum: 1
              maximum: 4094
              example: 1
        vlans:
          type: string
          example: 1,3,4
          description: Required for only vlan-aware v-nets (vlanAware == true)
        gateways:
          type: array
          items:
            type: object
            properties:
              prefix:
                type: string
                example: 10.0.0.1/24
              vlan:
                type: number
                example: 1
                description: Required for only vlan-aware v-nets (vlanAware == true)
              dhcpLeaseCount:
                type: number
                description: Count of DHCP leases for the current subnet
                example: 34
              dhcpEnabled:
                type: boolean
                description: Is DHCP service enabled for the V-Net
                example: true
              dhcp:
                type: object
                properties:
                  start:
                    type: string
                    example: 10.0.0.2
                  end:
                    type: string
                    example: 10.0.0.254
                  optionSet:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 21
                      name:
                        type: string
                        example: MyDefaultOptionSet
        tags:
          type: array
          items:
            type: string
          example:
            - tag1
            - tag2
    vnetPortBody:
        type: object
        properties:
          ports:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  example: 100
                state:
                  type: string
                  example: active
                vlan:
                  type: string
                  example: "16"
                accessMode:
                  type: boolean
                  example: false
                macCount:
                  type: number
                  example: 3
                ipv4Cidr:
                  type: string
                  example: "169.254.12.1/31"
                ipv6Cidr:
                  type: string
                  example: "fe80::e29:efff:fece:fb20/64"
    vnetPortEditBody:
      type: object
      properties:
        id:
          type: number
          example: 100
        state:
          type: string
          enum:
            - "active"
            - "disabled"
          example: active
        vlan:
          type: string
          example: "16"
        accessMode:
          type: boolean
          example: false
        ipv4Cidr:
          type: string
          example: "169.254.12.1/31"
        ipv6Cidr:
          type: string
          example: "fe80::e29:efff:fece:fb20/64"
    vnetResListBody:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/vnetsBody'
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    vnetResListByIdBody:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/vnetBody'
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    vnetResAddBody:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 2
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: ""
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    vnetResDeleteBody:
      type: object
      description: Success response
      properties:
        data:
          type: array
          items:
            type: object
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: ""
        isSuccess:
          type: boolean
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 200
    vnetResErrorBody:
      type: object
      description: Error response
      properties:
        data:
          type: array
          items:
            type: object
        errors:
          type: object
          example:
            property_name: Error message
          properties:
            key:
              type: string
        message:
          type: string
          example: Error message
        isSuccess:
          type: boolean
          example: false
        meta:
          type: object
          properties:
            apiVersion:
              type: string
              example: 2
            statusCode:
              type: integer
              example: 400
